/** Auto-generato da scripts/gen-capoluoghi-festivita.mjs (wikitext Wikipedia). Non editare a mano. */

export type CapoluogoFestivitaRow = {
  comune: string;
  comuneNorm: string;
  mese: number;
  giorno: number;
  nome: string;
};

export const CAPOLUOGO_FESTIVITA: readonly CapoluogoFestivitaRow[] = [
  { comune: "Agrigento", comuneNorm: "agrigento", mese: 2, giorno: 25, nome: "San Gerlando" },
  { comune: "Alessandria", comuneNorm: "alessandria", mese: 11, giorno: 10, nome: "San Baudolino" },
  { comune: "Ancona", comuneNorm: "ancona", mese: 5, giorno: 4, nome: "San Ciriaco" },
  { comune: "Aosta", comuneNorm: "aosta", mese: 9, giorno: 7, nome: "San Grato" },
  { comune: "Arezzo", comuneNorm: "arezzo", mese: 8, giorno: 7, nome: "San Donato d'Arezzo" },
  { comune: "Ascoli Piceno", comuneNorm: "ascoli piceno", mese: 8, giorno: 5, nome: "Sant'Emidio" },
  { comune: "Avellino", comuneNorm: "avellino", mese: 2, giorno: 14, nome: "San Modestino" },
  { comune: "Bari", comuneNorm: "bari", mese: 12, giorno: 6, nome: "San Nicola" },
  { comune: "Barletta", comuneNorm: "barletta", mese: 12, giorno: 30, nome: "San Ruggero" },
  { comune: "Belluno", comuneNorm: "belluno", mese: 11, giorno: 11, nome: "San Martino" },
  { comune: "Benevento", comuneNorm: "benevento", mese: 8, giorno: 24, nome: "San Bartolomeo apostolo" },
  { comune: "Bergamo", comuneNorm: "bergamo", mese: 8, giorno: 26, nome: "Sant'Alessandro di Bergamo" },
  { comune: "Biella", comuneNorm: "biella", mese: 12, giorno: 26, nome: "Santo Stefano" },
  { comune: "Bologna", comuneNorm: "bologna", mese: 10, giorno: 4, nome: "San Petronio" },
  { comune: "Bolzano", comuneNorm: "bolzano", mese: 8, giorno: 15, nome: "Maria Santissima Assunta" },
  { comune: "Brescia", comuneNorm: "brescia", mese: 2, giorno: 15, nome: "Santi Faustino e Giovita" },
  { comune: "Cagliari", comuneNorm: "cagliari", mese: 10, giorno: 30, nome: "San Saturnino di Cagliari" },
  { comune: "Caltanissetta", comuneNorm: "caltanissetta", mese: 9, giorno: 29, nome: "San Michele arcangelo" },
  { comune: "Campobasso", comuneNorm: "campobasso", mese: 4, giorno: 23, nome: "San Giorgio" },
  { comune: "Caserta", comuneNorm: "caserta", mese: 1, giorno: 20, nome: "San Sebastiano" },
  { comune: "Catania", comuneNorm: "catania", mese: 2, giorno: 5, nome: "Sant'Agata" },
  { comune: "Catanzaro", comuneNorm: "catanzaro", mese: 7, giorno: 16, nome: "San Vitaliano" },
  { comune: "Chieti", comuneNorm: "chieti", mese: 5, giorno: 11, nome: "San Giustino di Chieti" },
  { comune: "Como", comuneNorm: "como", mese: 8, giorno: 31, nome: "Sant'Abbondio" },
  { comune: "Cosenza", comuneNorm: "cosenza", mese: 2, giorno: 12, nome: "Madonna del Pilerio" },
  { comune: "Cremona", comuneNorm: "cremona", mese: 11, giorno: 13, nome: "Sant'Omobono" },
  { comune: "Crotone", comuneNorm: "crotone", mese: 10, giorno: 9, nome: "San Dionigi" },
  { comune: "Cuneo", comuneNorm: "cuneo", mese: 9, giorno: 29, nome: "San Michele Arcangelo" },
  { comune: "Enna", comuneNorm: "enna", mese: 7, giorno: 2, nome: "Madonna della Visitazione" },
  { comune: "Fermo", comuneNorm: "fermo", mese: 8, giorno: 15, nome: "Maria Santissima Assunta" },
  { comune: "Ferrara", comuneNorm: "ferrara", mese: 4, giorno: 23, nome: "San Giorgio" },
  { comune: "Firenze", comuneNorm: "firenze", mese: 6, giorno: 24, nome: "San Giovanni Battista" },
  { comune: "Foggia", comuneNorm: "foggia", mese: 3, giorno: 22, nome: "Madonna dei Sette Veli" },
  { comune: "Forlì", comuneNorm: "forli", mese: 2, giorno: 4, nome: "Madonna del Fuoco" },
  { comune: "Frosinone", comuneNorm: "frosinone", mese: 6, giorno: 20, nome: "San Silverio" },
  { comune: "Genova", comuneNorm: "genova", mese: 6, giorno: 24, nome: "San Giovanni Battista" },
  { comune: "Gorizia", comuneNorm: "gorizia", mese: 3, giorno: 16, nome: "Santi Ilario e Taziano" },
  { comune: "Grosseto", comuneNorm: "grosseto", mese: 8, giorno: 10, nome: "San Lorenzo" },
  { comune: "Imperia", comuneNorm: "imperia", mese: 11, giorno: 26, nome: "San Leonardo da Porto Maurizio" },
  { comune: "Isernia", comuneNorm: "isernia", mese: 5, giorno: 19, nome: "San Pietro Celestino" },
  { comune: "L'Aquila", comuneNorm: "l'aquila", mese: 6, giorno: 10, nome: "San Massimo d'Aveia" },
  { comune: "La Spezia", comuneNorm: "la spezia", mese: 3, giorno: 19, nome: "San Giuseppe" },
  { comune: "Latina", comuneNorm: "latina", mese: 4, giorno: 25, nome: "San Marco Evangelista" },
  { comune: "Lecce", comuneNorm: "lecce", mese: 8, giorno: 26, nome: "Sant'Oronzo" },
  { comune: "Lecco", comuneNorm: "lecco", mese: 12, giorno: 6, nome: "San Nicola" },
  { comune: "Livorno", comuneNorm: "livorno", mese: 5, giorno: 22, nome: "Santa Giulia" },
  { comune: "Lodi", comuneNorm: "lodi", mese: 1, giorno: 19, nome: "San Bassiano" },
  { comune: "Lucca", comuneNorm: "lucca", mese: 7, giorno: 12, nome: "San Paolino di Lucca" },
  { comune: "Macerata", comuneNorm: "macerata", mese: 8, giorno: 31, nome: "San Giuliano l'ospitaliere" },
  { comune: "Mantova", comuneNorm: "mantova", mese: 3, giorno: 18, nome: "Sant'Anselmo da Baggio" },
  { comune: "Massa", comuneNorm: "massa", mese: 10, giorno: 4, nome: "San Francesco d'Assisi" },
  { comune: "Matera", comuneNorm: "matera", mese: 7, giorno: 2, nome: "Madonna della Bruna" },
  { comune: "Messina", comuneNorm: "messina", mese: 6, giorno: 3, nome: "Madonna della Lettera" },
  { comune: "Milano", comuneNorm: "milano", mese: 12, giorno: 7, nome: "Sant'Ambrogio" },
  { comune: "Modena", comuneNorm: "modena", mese: 1, giorno: 31, nome: "San Geminiano" },
  { comune: "Monza", comuneNorm: "monza", mese: 6, giorno: 24, nome: "San Giovanni Battista" },
  { comune: "Napoli", comuneNorm: "napoli", mese: 9, giorno: 19, nome: "San Gennaro" },
  { comune: "Novara", comuneNorm: "novara", mese: 1, giorno: 22, nome: "San Gaudenzio" },
  { comune: "Nuoro", comuneNorm: "nuoro", mese: 8, giorno: 5, nome: "Nostra Signora della Neve" },
  { comune: "Oristano", comuneNorm: "oristano", mese: 2, giorno: 13, nome: "Sant'Archelao" },
  { comune: "Padova", comuneNorm: "padova", mese: 6, giorno: 13, nome: "Sant'Antonio di Padova" },
  { comune: "Palermo", comuneNorm: "palermo", mese: 7, giorno: 15, nome: "Santa Rosalia" },
  { comune: "Parma", comuneNorm: "parma", mese: 1, giorno: 13, nome: "Sant'Ilario di Poitiers" },
  { comune: "Pavia", comuneNorm: "pavia", mese: 12, giorno: 9, nome: "San Siro" },
  { comune: "Perugia", comuneNorm: "perugia", mese: 10, giorno: 4, nome: "San Costanzo di Perugia e santi patroni" },
  { comune: "Pesaro", comuneNorm: "pesaro", mese: 9, giorno: 24, nome: "San Terenzio di Pesaro" },
  { comune: "Pescara", comuneNorm: "pescara", mese: 10, giorno: 10, nome: "San Cetteo" },
  { comune: "Piacenza", comuneNorm: "piacenza", mese: 7, giorno: 4, nome: "Sant'Antonino di Piacenza" },
  { comune: "Pisa", comuneNorm: "pisa", mese: 6, giorno: 17, nome: "San Ranieri" },
  { comune: "Pistoia", comuneNorm: "pistoia", mese: 7, giorno: 25, nome: "San Jacopo" },
  { comune: "Pordenone", comuneNorm: "pordenone", mese: 4, giorno: 25, nome: "San Marco Evangelista" },
  { comune: "Potenza", comuneNorm: "potenza", mese: 5, giorno: 30, nome: "San Gerardo di Potenza" },
  { comune: "Prato", comuneNorm: "prato", mese: 12, giorno: 26, nome: "Santo Stefano" },
  { comune: "Ragusa", comuneNorm: "ragusa", mese: 8, giorno: 29, nome: "San Giovanni Battista e San Giorgio Martire" },
  { comune: "Ravenna", comuneNorm: "ravenna", mese: 7, giorno: 23, nome: "Sant'Apollinare" },
  { comune: "Reggio Calabria", comuneNorm: "reggio calabria", mese: 4, giorno: 23, nome: "San Giorgio" },
  { comune: "Reggio Emilia", comuneNorm: "reggio emilia", mese: 11, giorno: 24, nome: "San Prospero Vescovo" },
  { comune: "Rieti", comuneNorm: "rieti", mese: 12, giorno: 4, nome: "Santa Barbara" },
  { comune: "Rimini", comuneNorm: "rimini", mese: 10, giorno: 14, nome: "San Gaudenzio" },
  { comune: "Roma", comuneNorm: "roma", mese: 6, giorno: 29, nome: "Santi Pietro e Paolo" },
  { comune: "Rovigo", comuneNorm: "rovigo", mese: 11, giorno: 26, nome: "San Bellino" },
  { comune: "Salerno", comuneNorm: "salerno", mese: 9, giorno: 21, nome: "San Matteo Evangelista" },
  { comune: "Sassari", comuneNorm: "sassari", mese: 12, giorno: 6, nome: "San Nicola" },
  { comune: "Savona", comuneNorm: "savona", mese: 3, giorno: 18, nome: "Nostra Signora della Misericordia" },
  { comune: "Siena", comuneNorm: "siena", mese: 12, giorno: 1, nome: "Sant'Ansano" },
  { comune: "Siracusa", comuneNorm: "siracusa", mese: 12, giorno: 13, nome: "Santa Lucia" },
  { comune: "Sondrio", comuneNorm: "sondrio", mese: 6, giorno: 19, nome: "San Gervasio e San Protasio" },
  { comune: "Taranto", comuneNorm: "taranto", mese: 5, giorno: 10, nome: "San Cataldo" },
  { comune: "Teramo", comuneNorm: "teramo", mese: 12, giorno: 19, nome: "San Berardo da Pagliara" },
  { comune: "Terni", comuneNorm: "terni", mese: 2, giorno: 14, nome: "San Valentino" },
  { comune: "Torino", comuneNorm: "torino", mese: 6, giorno: 24, nome: "San Giovanni Battista" },
  { comune: "Trani", comuneNorm: "trani", mese: 5, giorno: 3, nome: "San Nicola Pellegrino" },
  { comune: "Trapani", comuneNorm: "trapani", mese: 8, giorno: 7, nome: "Sant'Alberto degli Abati" },
  { comune: "Trento", comuneNorm: "trento", mese: 6, giorno: 26, nome: "San Vigilio" },
  { comune: "Treviso", comuneNorm: "treviso", mese: 4, giorno: 27, nome: "San Liberale" },
  { comune: "Trieste", comuneNorm: "trieste", mese: 11, giorno: 3, nome: "San Giusto" },
  { comune: "Udine", comuneNorm: "udine", mese: 7, giorno: 12, nome: "Santi Ermacora e Fortunato" },
  { comune: "Urbino", comuneNorm: "urbino", mese: 6, giorno: 1, nome: "San Crescentino" },
  { comune: "Varese", comuneNorm: "varese", mese: 5, giorno: 8, nome: "San Vittore il Moro" },
  { comune: "Venezia", comuneNorm: "venezia", mese: 4, giorno: 25, nome: "San Marco Evangelista" },
  { comune: "Verbania", comuneNorm: "verbania", mese: 5, giorno: 8, nome: "San Vittore il Moro" },
  { comune: "Vercelli", comuneNorm: "vercelli", mese: 8, giorno: 1, nome: "Sant'Eusebio di Vercelli" },
  { comune: "Verona", comuneNorm: "verona", mese: 5, giorno: 21, nome: "San Zeno" },
  { comune: "Vibo Valentia", comuneNorm: "vibo valentia", mese: 3, giorno: 1, nome: "San Leoluca" },
  { comune: "Vicenza", comuneNorm: "vicenza", mese: 9, giorno: 8, nome: "Madonna di Monte Berico" },
  { comune: "Viterbo", comuneNorm: "viterbo", mese: 9, giorno: 4, nome: "Santa Rosa da Viterbo" }
];
